#!/usr/bin/env bash

# 🚀 QUICK START GUIDE - TriviaGamev3 Refactorizado
# Este archivo contiene instrucciones rápidas para empezar

echo "================================"
echo "🎮 TriviaGamev3 - Quick Start"
echo "================================"
echo ""

# 1. ENTENDER LA ESTRUCTURA
echo "1️⃣  ENTENDER LA ESTRUCTURA"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Lee estos archivos en orden:"
echo ""
echo "  1. README_TRIVIA.md"
echo "     └─ Resumen ejecutivo (5 min)"
echo ""
echo "  2. REFACTORIZATION_TRIVIA.md"
echo "     └─ Documentación técnica (10 min)"
echo ""
echo "  3. USAGE_EXAMPLES.md"
echo "     └─ Ejemplos prácticos (10 min)"
echo ""
echo "  4. BEST_PRACTICES.js"
echo "     └─ Patrones recomendados (referencia)"
echo ""
echo "  5. CHECKLIST.md"
echo "     └─ Lista de validación (referencia)"
echo ""

# 2. ARCHIVOS PRINCIPALES
echo "2️⃣  ARCHIVOS PRINCIPALES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Estos son los archivos modificados/creados:"
echo ""
echo "  📁 src/hooks/triviav2/"
echo "     └─ useTriviaGame.js (Hook con lógica)"
echo ""
echo "  📁 src/components/games/trivia/"
echo "     ├─ TriviaComponents.jsx (Componentes UI)"
echo "     └─ TriviaScreens.jsx (Pantallas completas)"
echo ""
echo "  📄 src/pages/games/"
echo "     └─ TriviaGamev3.jsx (Componente principal)"
echo ""

# 3. DESARROLLO LOCAL
echo "3️⃣  DESARROLLO LOCAL"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Pasos para empezar:"
echo ""
echo "  $ npm install          # Si es necesario"
echo "  $ npm run dev          # Iniciar servidor de desarrollo"
echo ""
echo "  La aplicación estará en:"
echo "  👉 http://localhost:5173"
echo ""

# 4. TESTING MANUAL
echo "4️⃣  TESTING MANUAL"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Checklist de pruebas:"
echo ""
echo "  ✓ Cargar el juego (debe mostrar 'Preparando preguntas...')"
echo "  ✓ Esperar cuenta regresiva (3, 2, 1, ¡YA!)"
echo "  ✓ Responder una pregunta correcta"
echo "  ✓ Responder una pregunta incorrecta"
echo "  ✓ Esperar que se agote el tiempo"
echo "  ✓ Verificar cálculo de puntos"
echo "  ✓ Verificar racha (combo)"
echo "  ✓ Completar juego y ver resultados"
echo "  ✓ Hacer clic en 'Jugar de nuevo'"
echo "  ✓ Probar en móvil (responsive)"
echo ""

# 5. USAR EL HOOK EN OTRO LUGAR
echo "5️⃣  USAR EL HOOK EN OTRO LUGAR"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Si quieres usar el hook en otro componente:"
echo ""
echo "  import { useTriviaGame } from '../../hooks/triviav2/useTriviaGame';"
echo ""
echo "  function MyComponent() {"
echo "    const { questions, handleAnswer, points } = useTriviaGame(profile);"
echo "    // Tu código aquí"
echo "  }"
echo ""

# 6. TROUBLESHOOTING
echo "6️⃣  TROUBLESHOOTING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Si encuentras errores:"
echo ""
echo "  ❌ Error de import"
echo "     └─ Verifica la ruta del archivo"
echo "     └─ Asegúrate que existan los archivos"
echo ""
echo "  ❌ Error de Supabase"
echo "     └─ Verifica credenciales en .env"
echo "     └─ Revisa la conexión a BD"
echo ""
echo "  ❌ Animaciones cortadas"
echo "     └─ Verifica que Framer Motion esté instalado"
echo "     └─ npm install framer-motion"
echo ""
echo "  ❌ Estilos no aparecen"
echo "     └─ Verifica que Tailwind CSS esté configurado"
echo "     └─ Revisa tailwind.config.js"
echo ""

# 7. PRÓXIMOS PASOS
echo "7️⃣  PRÓXIMOS PASOS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Para mejorar aún más:"
echo ""
echo "  🔄 Tests unitarios"
echo "     └─ npm install --save-dev @testing-library/react"
echo ""
echo "  📊 Performance profiling"
echo "     └─ npm run build"
echo "     └─ Usar React DevTools"
echo ""
echo "  📚 Storybook (para componentes)"
echo "     └─ npx sb init"
echo ""
echo "  🔍 Error boundary"
echo "     └─ Ver BEST_PRACTICES.js"
echo ""

# 8. REFERENCIA RÁPIDA
echo "8️⃣  REFERENCIA RÁPIDA"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Hook exportado:"
echo "  ├─ questions: Question[]"
echo "  ├─ currentQuestion: Question"
echo "  ├─ gameState: 'loading' | 'starting' | 'playing' | 'finished' | 'error'"
echo "  ├─ points: number"
echo "  ├─ score: number"
echo "  ├─ streak: number"
echo "  ├─ selectedOption: number | null"
echo "  ├─ timeLeft: number"
echo "  ├─ handleAnswer(index): void"
echo "  └─ handleReset(): void"
echo ""

echo "================================"
echo "✅ ¡Listo para comenzar!"
echo "================================"
echo ""
echo "Preguntas? Consulta:"
echo "  📖 README_TRIVIA.md"
echo "  📖 USAGE_EXAMPLES.md"
echo "  📖 INDEX.md"
echo ""
