export const messages = [
  {
    title: "Este usuario no existe 🕵️",
    desc: "Lo buscamos… pero ni sus amigos lo encuentran 😬",
    desc2: "Capaz escribió mal su propio username",
    btnBack: "Disimular 😅",
    btnHome: "Volver al inicio 🏠",
    btnExplore: "Explorar gente 🔍",
    btnTroll: "Seguir buscando 🤡",
    extra: "Misión fallida",
  },
  {
    title: "Perfil desaparecido 🫥",
    desc: "O nunca existió… o fue demasiado legendario",
    btnBack: "Volver lento 🐢",
    btnHome: "Ir al inicio 🏠",
    btnExplore: "Descubrir otros 👀",
    btnTroll: "Teoría conspirativa 🧠",
    extra: "Caso sin resolver",
  },
  {
    title: "Usuario no encontrado 🚫",
    desc: "Revisamos todo… incluso debajo de la cama 🛏️",
    btnBack: "Salir con dignidad 😌",
    btnHome: "Inicio 🏠",
    btnExplore: "Buscar otro 🔍",
    btnTroll: "Llamar a la policía 🚓",
  },
  {
    title: "Ese perfil se fue 🏃",
    desc: "Y no dejó ni bio… ni rastro",
    desc2: "Respeta su decisión 😌",
    btnBack: "Aceptar 😔",
    btnHome: "Seguir adelante 🏠",
    btnExplore: "Conocer gente nueva 😎",
    btnTroll: "Stalkear más 🕵️",
  },
  {
    title: "¿De verdad esperabas encontrar a alguien? 🤨",
    desc: "Interesante nivel de optimismo…",
    desc2: "Spoiler: no existe",
    btnBack: "Retirarme en silencio 😶",
    btnHome: "Resetear vida 🔄",
    btnExplore: "Bajar expectativas 📉",
    btnTroll: "Intentar otra vez 🤡",
    extra: "Modo oscuro = sinceridad brutal",
  },
  {
    title: "Este usuario está más perdido que tú 💀",
    desc: "Y eso ya es decir bastante",
    btnBack: "Volver lentamente 😐",
    btnHome: "Ir al inicio 🏠",
    btnExplore: "Buscar algo real 🔍",
    btnTroll: "Negar la realidad 🙃",
    extra: "Nivel de negación alto",
  },
  {
    title: "No existe. Así de simple 😌",
    desc: "Pero gracias por intentarlo",
    desc2: "El esfuerzo se valora… supongo",
    btnBack: "Aceptar derrota 😔",
    btnHome: "Inicio 🏠",
    btnExplore: "Distraerme 🔍",
    btnTroll: "Seguir insistiendo 💀",
  },
  {
    title: "404: persona no encontrada 🧍",
    desc: "Tal vez era mejor así",
    btnBack: "Salir de aquí 🚪",
    btnHome: "Volver 🏠",
    btnExplore: "Buscar alguien real 😶",
    btnTroll: "Crear teorías 🧠",
    extra: "Esto se puso incómodo",
  },
];
