export const messages = [
  {
    title: "Esta publicación se fue por ceviche 🐟",
    desc: "No volvió… y sinceramente, no la culpamos 😌",
    desc2: "Probablemente está en la playa viviendo su mejor vida 🌊",
    btnBack: "Volver sin hacer ruido 🤫",
    btnHome: "Ir al inicio 🏠",
    btnGame: "Ir a jugar 🎮",
    btnTroll: "Buscarla en la costa 🏖️",
    extra: "Prioridades: ceviche > internet",
  },
  {
    title: "404… pero con flow 😎",
    desc: "Aquí no hay nada, pero al menos te ves bien buscándolo",
    desc2: "Confianza nivel: injustificada 💅",
    btnBack: "Retroceder con estilo 🕶️",
    btnHome: "Ir al inicio 🏠",
    btnGame: "Modo pro gamer 🎮",
    btnTroll: "Seguir posando 📸",
    extra: "Flow intacto, contenido no",
  },
  {
    title: "Se fue más rápido que quincena 💸",
    desc: "Y tú llegaste tarde… como siempre 😬",
    desc2: "No te preocupes, no eres el único 😅",
    btnBack: "Volver arrepentido 😔",
    btnHome: "Administrar mejor mi vida 🏠",
    btnGame: "Olvidar mis decisiones 🎮",
    btnTroll: "Revisar otra vez 🤡",
    extra: "Educación financiera pendiente 📉",
  },
  {
    title: "Ups… esto ya no existe 👻",
    desc: "Tal vez nunca debiste encontrarlo...",
    desc2: "O tal vez nunca debió existir 😶‍🌫️",
    btnBack: "Salir silenciosamente 👣",
    btnHome: "Volver al mundo real 🏠",
    btnGame: "Escapar de la matrix 🎮",
    btnTroll: "Invocar de nuevo 🧙",
    extra: "Nivel paranormal detectado",
  },
  {
    title: "Contenido eliminado 🚫",
    desc: "O escondido… estilo ninja 🥷",
    desc2: "Demasiado rápido para tus ojos 👀",
    btnBack: "Retirarse estratégicamente 🧠",
    btnHome: "Volver al inicio 🏠",
    btnGame: "Entrenar reflejos 🎮",
    btnTroll: "Buscar pistas 🔍",
    extra: "Sigilo nivel experto",
  },
  {
    title: "Esta publicación se fue AFK 🎮",
    desc: "Probablemente está en otra partida ahora mismo",
    desc2: "Y no te invitó… eso duele 😔",
    btnBack: "Salir de la partida 🚪",
    btnHome: "Volver al lobby 🏠",
    btnGame: "Unirme a otra partida 🎮",
    btnTroll: "Esperarla eternamente ⏳",
    extra: "AFK pero feliz",
  },
  // 🔥 COMPLETADOS + MEJORADOS
  {
    title: "Esta publicación se fue… y no dejó ubicación 📍",
    desc: "Puede que haya sido eliminada, escondida… o simplemente nunca fue para ti 👀",
    desc2: "(sí, duele… pero seguimos 💪)",
    btnBack: "Volver como si nada 😎",
    btnHome: "Resetear mi vida 🔄",
    btnGame: "Escape gamer 🎮",
    btnTroll: "Buscar sentido a mi vida 🫠",
    extra: "Error 404 emocional 💔",
  },
  {
    title: "404 pero con actitud 😎",
    desc: "Esta publicación no está… y no va a volver.",
    desc2: "Aceptación es el primer paso 😌",
    btnBack: "Me equivoqué, perdón 😅",
    btnHome: "Resetear mi vida 🔄",
    btnGame: "Escape gamer 🎮",
    btnTroll: "Negar la realidad 🙃",
    extra: "Nivel de negación: experto",
  },
  {
    title:
      "Esta publicación desapareció más rápido que tu dinero en quincena 💸",
    desc: "O la borraron… o nunca estuvo destinada para ti 😶‍🌫️",
    btnBack: "Retroceder con dignidad 😌",
    btnHome: "Volver al inicio antes que duela más 🏠",
    btnGame: "Olvidarlo jugando 🎮",
    btnTroll: "Llorar en silencio 😭",
    extra: "F en el chat",
  },
  {
    title: "Ups… esta publicación se fue de viaje ✈️",
    desc: "Puede que haya sido eliminada o que no tengas permiso para verla.",
    desc2: "Pero tranqui, hay mucho más que explorar 👀",
    btnBack: "Volver como un crack 😎",
    btnHome: "Ir al inicio 🏠",
    btnGame: "Ir a jugar 🎮",
    btnTroll: "Ir al infinito y más allá 🚀",
  },

  // 😈 NUEVAS VARIANTES (más humor)
  {
    title: "Nada por aquí… sigue scrolleando 🌀",
    desc: "Literalmente no hay nada. Ni pistas. Ni esperanza.",
    desc2: "Pero hey… lo intentaste 👏",
    btnBack: "Intentar disimular 😅",
    btnHome: "Volver a la realidad 🏠",
    btnGame: "Escapar jugando 🎮",
    btnTroll: "Insistir sin sentido 🤡",
  },
  {
    title: "Esta publicación está más perdida que tú un lunes 😵",
    desc: "No sabemos dónde está… ni si volverá",
    btnBack: "Volver lento pero seguro 🐢",
    btnHome: "Reiniciar cerebro 🔄",
    btnGame: "Modo distracción 🎮",
    btnTroll: "Pánico existencial 😱",
    extra: "Estado mental: cuestionable",
  },
  {
    title: "Te ilusionaste… pero no 😔",
    desc: "Aquí no hay publicación, solo decepción",
    desc2: "Pero tranquilo, no es la primera vez 😏",
    btnBack: "Huir elegantemente 🕶️",
    btnHome: "Volver al inicio 🏠",
    btnGame: "Tapar el dolor 🎮",
    btnTroll: "Negarlo todo 🙅",
  },
  {
    title: "Error 404: motivación no encontrada 😪",
    desc: "Ni la publicación… ni las ganas de seguir",
    btnBack: "Volver sin ganas 😶",
    btnHome: "Automáticamente al inicio 🤖",
    btnGame: "Dopamina rápida 🎮",
    btnTroll: "Seguir intentando 💀",
    extra: "Sistema emocional colapsando...",
  },
  {
    title: "Esto está más vacío que tu refri a fin de mes 🥲",
    desc: "No hay nada aquí… ni migajas",
    btnBack: "Cerrar con dignidad 🚪",
    btnHome: "Buscar comida 🏠",
    btnGame: "Ignorar la realidad 🎮",
    btnTroll: "Abrir otra vez 🤡",
  },
  {
    title: "La publicación dijo: ‘me voy’ 🏃",
    desc: "Y no miró atrás…",
    desc2: "Respeta su decisión 😌",
    btnBack: "Aceptar el rechazo 😔",
    btnHome: "Seguir adelante 🏠",
    btnGame: "Distraerte 🎮",
    btnTroll: "Stalkear de nuevo 🕵️",
  },
  {
    title: "No era para ti… supéralo 😌",
    desc: "Hay cosas en la vida que simplemente no pasan",
    btnBack: "Intentar otra vez 🤞",
    btnHome: "Volver al inicio 🏠",
    btnGame: "Evitar sentimientos 🎮",
    btnTroll: "Sobrepensar 🧠",
    extra: "Te va a doler un ratito",
  },
  {
    title: "Aquí no hay nada… literal nada 🫥",
    desc: "Ni bugs, ni contenido… solo vacío existencial",
    btnBack: "Volver lento 😐",
    btnHome: "Resetear universo 🌌",
    btnGame: "Modo escape 🎮",
    btnTroll: "Mirar fijamente 👁️",
  },
  {
    title: "Se buggeó la realidad 🧠💥",
    desc: "La publicación desapareció del sistema",
    desc2: "Estamos tan confundidos como tú",
    btnBack: "Reintentar 🧪",
    btnHome: "Reiniciar sistema 🔄",
    btnGame: "Distracción inmediata 🎮",
    btnTroll: "Hackear la matrix 🕶️",
    extra: "Glitch detected",
  },
  {
    title: "Nada que ver aquí… sigue nomás 👀",
    desc: "Te prometo que no vale la pena quedarte",
    btnBack: "Ok, me voy 😅",
    btnHome: "Ir al inicio 🏠",
    btnGame: "Ir a jugar 🎮",
    btnTroll: "Quedarme igual 🤨",
  },
];
