export const commentThreadMessages = [
  {
    title: "Este hilo se quedó en visto 👀",
    desc: "Nadie respondió… y duele más de lo que debería 😔",
    desc2: "Quizá escribiste demasiado… o demasiado poco 😅",
    btnBack: "Retirarme con dignidad 🚶",
    btnHome: "Volver al inicio 🏠",
    btnGame: "Olvidar esto jugando 🎮",
    btnTroll: "Esperar respuesta ⏳",
    extra: "Visto ✔️ pero ignorado",
  },
  {
    title: "Comentarios desaparecidos 🫥",
    desc: "Aquí debería haber una discusión interesante… pero nope",
    desc2: "Silencio absoluto 🔇",
    btnBack: "Salir en silencio 🤫",
    btnHome: "Ir al inicio 🏠",
    btnGame: "Buscar dopamina 🎮",
    btnTroll: "Responderme solo 🤡",
    extra: "Nivel de interacción: 0",
  },
  {
    title: "Este hilo murió joven 💀",
    desc: "Nació con potencial… pero nadie lo continuó",
    desc2: "F en el chat 😔",
    btnBack: "Aceptar la derrota 😌",
    btnHome: "Volver al inicio 🏠",
    btnGame: "Ir a jugar 🎮",
    btnTroll: "Revivirlo artificialmente 🧪",
    extra: "Duración: demasiado corta",
  },
  {
    title: "Sin comentarios… como tus mensajes 🥲",
    desc: "Nadie dijo nada… absolutamente nada",
    desc2: "Ni tu crush respondió así 😭",
    btnBack: "Cerrar esto 😶",
    btnHome: "Ir al inicio 🏠",
    btnGame: "Distraerme 🎮",
    btnTroll: "Refrescar 10 veces 🔄",
    extra: "Autoestima en mantenimiento",
  },
  {
    title: "Este hilo se fue AFK 💬🎮",
    desc: "La conversación empezó… pero nadie volvió",
    desc2: "Clásico abandono 😔",
    btnBack: "Salir del chat 🚪",
    btnHome: "Volver al lobby 🏠",
    btnGame: "Unirme a otra conversación 🎮",
    btnTroll: "Esperar eternamente ⏳",
    extra: "AFK pero con estilo",
  },
  {
    title: "Nada por discutir aquí 🤷",
    desc: "Ni opiniones, ni peleas, ni drama",
    desc2: "Internet falló en su misión 😐",
    btnBack: "Retirarme pacíficamente 🕊️",
    btnHome: "Volver al inicio 🏠",
    btnGame: "Crear caos en otro lado 🎮",
    btnTroll: "Iniciar pelea solo 🔥",
    extra: "0% toxicidad (raro)",
  },
  {
    title: "El hilo se rompió 🧵💥",
    desc: "Algo pasó… y los comentarios desaparecieron",
    desc2: "Ni nosotros sabemos qué ocurrió 😵",
    btnBack: "Reintentar 🔄",
    btnHome: "Reiniciar todo 🏠",
    btnGame: "Ignorar esto 🎮",
    btnTroll: "Culpar al sistema 🧠",
    extra: "Glitch social detectado",
  },
  {
    title: "Llegaste tarde al chisme 🕵️",
    desc: "Aquí hubo conversación… pero ya no queda nada",
    desc2: "Te perdiste lo bueno 😬",
    btnBack: "Irme lentamente 🐢",
    btnHome: "Volver al inicio 🏠",
    btnGame: "Buscar otro drama 🎮",
    btnTroll: "Inventar contexto 🤡",
    extra: "Chisme expirado ⏰",
  },
  {
    title: "Este hilo está más vacío que grupo sin tareas 🥲",
    desc: "Nadie comentó… ni por compromiso",
    desc2: "Duro, pero real 😅",
    btnBack: "Salir con pena 😔",
    btnHome: "Volver al inicio 🏠",
    btnGame: "Modo distracción 🎮",
    btnTroll: "Escribir algo random 🧠",
    extra: "Participación: inexistente",
  },
  {
    title: "Comentario no encontrado 🚫",
    desc: "Puede que lo borraron… o nunca existió",
    desc2: "Misterio nivel internet 🕵️",
    btnBack: "Volver como si nada 😎",
    btnHome: "Ir al inicio 🏠",
    btnGame: "Escape gamer 🎮",
    btnTroll: "Buscar pruebas 🔍",
    extra: "Teoría conspirativa activada",
  },
];