export const blogMessages = [
  {
    title: "Este blog se fue por café ☕",
    desc: "Dijo que volvía en 5 minutos… han pasado años 😔",
    desc2: "Probablemente está escribiendo el mejor artículo de la historia… o no 😅",
    btnBack: "Cerrar sin hacer ruido 🤫",
    btnHome: "Volver al inicio 🏠",
    btnGame: "Procrastinar 🎮",
    btnTroll: "Esperar el artículo ⏳",
    extra: "Inspiración en proceso...",
  },
  {
    title: "404… pero con ideas profundas 🧠",
    desc: "El artículo no está… pero seguro iba a cambiar tu vida",
    desc2: "O al menos hacerte sentir productivo 😌",
    btnBack: "Volver reflexivo 🤓",
    btnHome: "Ir al inicio 🏠",
    btnGame: "Ignorar mi crecimiento 🎮",
    btnTroll: "Fingir que lo leí 📖",
    extra: "Sabiduría no encontrada",
  },
  {
    title: "Este artículo nunca se publicó 📝",
    desc: "Se quedó en borrador… como tus metas 😬",
    desc2: "Algún día verá la luz… tal vez 😅",
    btnBack: "Volver con culpa 😔",
    btnHome: "Reiniciar mi vida 🏠",
    btnGame: "Evadir responsabilidades 🎮",
    btnTroll: "Culpar a la inspiración 🤡",
    extra: "Estado: en desarrollo eterno",
  },
  {
    title: "Contenido eliminado 🚫",
    desc: "El autor dijo: ‘mejor no’",
    desc2: "Y sinceramente… lo respetamos 😌",
    btnBack: "Retirarme discretamente 👣",
    btnHome: "Volver al inicio 🏠",
    btnGame: "Olvidar esto 🎮",
    btnTroll: "Imaginar el contenido 🧠",
    extra: "Autocensura activada",
  },
  {
    title: "Este blog está más vacío que tu motivación un lunes 😴",
    desc: "Nada que leer… ni excusas para procrastinar",
    desc2: "Duro golpe 😬",
    btnBack: "Cerrar con resignación 😔",
    btnHome: "Volver al inicio 🏠",
    btnGame: "Buscar dopamina 🎮",
    btnTroll: "Refrescar sin sentido 🔄",
    extra: "Lectura cancelada",
  },
  {
    title: "El autor se fue AFK ✍️🎮",
    desc: "Empezó el artículo… pero nunca volvió",
    desc2: "Clásico escritor 😌",
    btnBack: "Salir del blog 🚪",
    btnHome: "Volver al lobby 🏠",
    btnGame: "Unirme a otra historia 🎮",
    btnTroll: "Esperar actualización ⏳",
    extra: "Creatividad pausada",
  },
  {
    title: "Llegaste tarde al contenido ⏰",
    desc: "Aquí había un artículo… pero ya no está",
    desc2: "Te perdiste lo bueno 😬",
    btnBack: "Irme lento 🐢",
    btnHome: "Volver al inicio 🏠",
    btnGame: "Buscar otro blog 🎮",
    btnTroll: "Inventar de qué trataba 🤡",
    extra: "Contenido expirado",
  },
  {
    title: "Este artículo se fue viral… y luego desapareció 🌪️",
    desc: "Duró poco, pero dejó huella",
    desc2: "Ahora solo queda el recuerdo 😔",
    btnBack: "Aceptar la realidad 😌",
    btnHome: "Volver al inicio 🏠",
    btnGame: "Distraerme 🎮",
    btnTroll: "Buscar capturas 📸",
    extra: "Leyenda urbana del internet",
  },
  {
    title: "Nada por leer aquí… increíble 🫠",
    desc: "Viniste con ganas de aprender… mala decisión",
    desc2: "Internet te falló hoy 😅",
    btnBack: "Cerrar pestaña 😶",
    btnHome: "Volver al inicio 🏠",
    btnGame: "Modo escape 🎮",
    btnTroll: "Quedarme igual 🤨",
    extra: "Productividad: cancelada",
  },
  {
    title: "Este blog no era para ti 😌",
    desc: "Tal vez no tienes acceso… o el destino dijo que no",
    desc2: "Y el destino nunca se equivoca 😏",
    btnBack: "Aceptar 😔",
    btnHome: "Volver al inicio 🏠",
    btnGame: "Ignorar sentimientos 🎮",
    btnTroll: "Intentar otra vez 🤡",
    extra: "Dolor leve detectado",
  },
  {
    title: "Se buggeó el conocimiento 🧠💥",
    desc: "El artículo desapareció del sistema",
    desc2: "Estamos igual de confundidos que tú 😵",
    btnBack: "Reintentar 🧪",
    btnHome: "Reiniciar todo 🏠",
    btnGame: "Distracción rápida 🎮",
    btnTroll: "Hackear la sabiduría 🕶️",
    extra: "Error intelectual 404",
  },
  {
    title: "Mucho texto… ah no, nada 📄",
    desc: "Venías preparado para leer… pero no hay nada",
    desc2: "Plot twist inesperado 😅",
    btnBack: "Cerrar decepcionado 😔",
    btnHome: "Volver al inicio 🏠",
    btnGame: "Olvidarlo jugando 🎮",
    btnTroll: "Inventar el artículo 🤡",
    extra: "Lectura imaginaria",
  },
  {
    title: "Este artículo se perdió en el algoritmo 🤖",
    desc: "Ni nosotros sabemos dónde terminó",
    desc2: "El algoritmo hace lo que quiere 😶‍🌫️",
    btnBack: "Salir confundido 😐",
    btnHome: "Volver al inicio 🏠",
    btnGame: "Ignorar el sistema 🎮",
    btnTroll: "Culpar a la IA 🤡",
    extra: "Algoritmo 1 - Usuario 0",
  },
  {
    title: "Te ilusionaste con leer… pero no 😔",
    desc: "Aquí no hay contenido, solo decepción",
    desc2: "Pero tranquilo, ya es costumbre 😏",
    btnBack: "Huir elegantemente 🕶️",
    btnHome: "Volver al inicio 🏠",
    btnGame: "Tapar el dolor 🎮",
    btnTroll: "Negarlo todo 🙅",
    extra: "F en el blog",
  },
];